const PLOT_WIDTH = 600
const PLOT_HEIGHT = 460
const CYTOF_HISTOGRAM_WIDTH = Math.min(PLOT_WIDTH, PLOT_HEIGHT) * 0.10
const CYTOF_HISTOGRAM_HEIGHT = Math.min(PLOT_WIDTH, PLOT_HEIGHT) * 0.10

export default {
    // Scales
    SCALE_LINEAR: 'SCALE_LINEAR',
    SCALE_LOG: 'SCALE_LOG',
    SCALE_BIEXP: 'SCALE_BIEXP',
    SCALE_ARCSIN: 'SCALE_ARCSIN',
    // Machine Types
    MACHINE_CYTOF: 'CYTOF',
    MACHINE_FLORESCENT: 'FLORESCENT',
    // Gate types
    GATE_TYPE_POLYGON: 'GATE_TYPE_POLYGON',
    // Gate creators
    GATE_CREATOR_MANUAL: 'GATE_CREATOR_MANUAL',
    GATE_CREATOR_PERSISTENT_HOMOLOGY: 'GATE_CREATOR_PERSISTENT_HOMOLOGY',
    // Integer constants
    PLOT_WIDTH: PLOT_WIDTH,
    PLOT_HEIGHT: PLOT_HEIGHT,
    CYTOF_HISTOGRAM_WIDTH: CYTOF_HISTOGRAM_WIDTH,
    CYTOF_HISTOGRAM_HEIGHT: CYTOF_HISTOGRAM_HEIGHT,
}